name: Workflow de Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fazendo checkout
        uses: actions/checkout@v4

      - name: Instalando .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Restaurando dependências
        run: dotnet restore MotosApi/MotosApi.csproj

      - name: Compilando o projeto
        run: dotnet build MotosApi/MotosApi.csproj --configuration Release

      - name: Executando aplicação
        run: dotnet run --project MotosApi/MotosApi.csproj --configuration Release
